# Generated by Django 6.0.6 on 2026-06-28 12:35

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Build',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('slug', models.SlugField(unique=True, verbose_name='URL-slug')),
                ('category', models.CharField(choices=[('gaming', 'Игровой'), ('work', 'Рабочий'), ('study', 'Учебный'), ('universal', 'Универсальный')], max_length=20, verbose_name='Категория')),
                ('price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена (BYN)')),
                ('description', models.TextField(verbose_name='Описание')),
                ('cpu', models.CharField(max_length=200, verbose_name='Процессор')),
                ('gpu', models.CharField(max_length=200, verbose_name='Видеокарта')),
                ('ram', models.CharField(max_length=100, verbose_name='Оперативная память')),
                ('storage', models.CharField(max_length=100, verbose_name='Накопитель')),
                ('case', models.CharField(max_length=100, verbose_name='Корпус')),
                ('is_popular', models.BooleanField(default=False, verbose_name='Хит продаж')),
                ('image', models.ImageField(blank=True, upload_to='builds/', verbose_name='Изображение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
            ],
            options={
                'verbose_name': 'Сборка',
                'verbose_name_plural': 'Сборки',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Имя')),
                ('contact', models.CharField(max_length=100, verbose_name='Контакт')),
                ('budget', models.CharField(choices=[('up_to_500', 'До 500$'), ('500_800', '500–800$'), ('800_1200', '800–1200$'), ('1200_plus', '1200$+')], max_length=20, verbose_name='Бюджет')),
                ('purpose', models.CharField(choices=[('games', 'Игры'), ('work', 'Работа'), ('study', 'Учёба'), ('all', 'Всё сразу')], max_length=20, verbose_name='Цель')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('is_processed', models.BooleanField(default=False, verbose_name='Обработана')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('build', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='shop.build', verbose_name='Выбранная сборка')),
            ],
            options={
                'verbose_name': 'Заявка',
                'verbose_name_plural': 'Заявки',
                'ordering': ['-created_at'],
            },
        ),
    ]
